a = float(input("A: "))
b = float(input("B: "))
c = float(input("C: "))
ac = abs(a - c)
bc = abs(b - c)
ab = abs(a - b)
result = ac + bc
print("A-C: ", ac)
print("B-C: ", bc)
print("Сумма: ", result)
print("A-B: ", ab)