x1 = float(input("X1 = "))
y1 = float(input("Y1 = "))
x2 = float(input("X2 = "))
y2 = float(input("Y2 = "))
print("(x1, y1): ({0},{1})".format(x1, y1))
print("(x2, y2): ({0},{1})".format(x2, y2))
x = abs(x1 - x2)
y = abs(y1- x2)
p = 2 * (x + y)
s = x * y
print("Сторона X: ", x)
print("Сторона Y: ", y)
print("Периметр прямоугольника: ", p)
print("Площадь прямоугольника: ", s)